version: '3'

services:
  server:
    container_name: NODEJS_SERVER_MCFADYEN
    build: .
    command: npm start
    volumes:
      - ./:/node-app
      - node-app/node_modules
    environment:
      NODE_ENV: development
    depends_on:
      - db
    links:
      - db
    ports:
      - '9000:9000'

  db:
    image: 'mongo'
    container_name: MONGODB_MCFADYEN
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/db